# Project information
site_name: Xytech API Documentation
site_url: https://xytechsystems.github.io/documentation/

# Repository
#repo_url: https://github.com/xytechsystems/documentation
#edit_uri: /tree/main/docs

# Copyright
copyright: Copyright &copy; 2025 Xytech Systems Inc.

# Configuration
theme:
  name: material
  features:
    #- navigation.path
    - navigation.instant
    - navigation.footer
    - navigation.sections # Enable sections are rendered as groups
    - navigation.expand # Expand sections by default
    - navigation.tracking #the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    - navigation.tabs   #When tabs are enabled, top-level sections are rendered in a menu layer below the header
    - navigation.tabs.sticky #Always show when scrolling down a page                                                                  

  logo: assets/xLogo.png

  palette: 
    # Palette toggle for light mode
    - scheme: xytech
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


# Hide Made with MKDocs
extra:
  generator: false  

   
plugins:
    - search
    - glightbox
    - callouts
    - mkdocs-nav-weight: #Plugin to set display order of pages
       section_renamed: false
       index_weight: -10
       warning: true
       reverse: false
       headless_included: false
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - nl2br # newlines to be treated as hard breaks
  - pymdownx.highlight: #code syntax highlighting
  #    linenums: true    #add line numbers to code blocks
  - pymdownx.superfences 
  - admonition          #Add call-outs formatting
  - pymdownx.details    # call outs 
  - def_list            #add bullet lists  
  - pymdownx.tasklist:  #add check box lists
      custom_checkbox: true



# Omit authentication providers - not relevant to API docs
exclude_docs: |
 /Auth Providers/

# omit home page from navigation
not_in_nav: |
 /index.md          
   

draft_docs:
  drafts/  # A "drafts" directory anywhere.
